# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dacfdbe0bab3b7dc4a36028460245777832ec7879df5238da73cadc99f4804cae737c60eb3bf06190c879bc8b9f6d896ffdfbee5be0b5e7419509412f4a2e427

test:
  secret_key_base: e5fb6ffec0cf721d580663bf77bdfa55f9c1ff24a10599ac4913912e3c2db4602a00b92e4642dedecff48cfa44fd5661bdb874ab9db893ae3c805ad3fbe936a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
